### ISSUE TITLE
flush might not flush on the first second of the app

### ISSUE THREAD

**Issue by izikl** [bitstadium/HockeySDK-Windows#109]
[SDK initialization is postponed by 1 sec](https://github.com/bitstadium/HockeySDK-Windows/blob/develop/Src/Kit.Core45/WindowsAppInitializer.cs#L42) to avoid performance hit which might slow down app startup. 

Therefore the persistence channel (an internal object that persist telemetry before sending it) is not yet created and [calling flush will result in a no-op](https://github.com/bitstadium/HockeySDK-Windows/blob/develop/Src/Kit.Core45/HockeyClient.cs#L1205).

**Comment by quincycs** [comment]
#75 is related.  If app crashes quickly then crash wouldn't be logged. 

And UWP bg task usage is related. 
For the scenario of initializing the HA SDK from a UWP background task.  

We would want to log some custom event and flush it then allow exit of the background task. 

1. You can't flush immediately after HA SDK initialization
2. You don't know when the flush has succeeded in order to exit.

**Comment by ChristopheLav** [comment]
Not related directly to the main problem, but I have implemented Background Tasks support with some fixes and a new  FlushAndSendPersistentTelemetry(...) method to ensure data are send (flush succeeded) before terminate the background task execution. 

My PR #62 contain this - but it's refuse by the HockeyApp SDK team because they have no plan to support this actually. The PR branch in my fork is up-to-date with last source. 

Maybe this is answer your point number two.

**Comment by elamalani** [comment]
@quincycs Thanks for all the input here. We are working hard on [App Center ](https://appcenter.ms) and are not planning to fix this for HockeyApp SDK.
