### ISSUE TITLE
AppDomain.Current.UnhandledException doesn't work with Windows Forms SDK

### ISSUE THREAD

**Issue by writeline** [bitstadium/HockeySDK-Windows#33]
When configuring the HockeyApp Client with 

```
HockeyApp.Current.Configure("myappid", false);
```

I never get log files written probably. I tried to debug this down, it seems that writing async to the file System in this case is throwing an unhandled system exception. After using `SendCrashesAsync()` I get this stack trace

```
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bei System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   bei HockeyApp.Model.CrashData.Deserialize(Stream inputStream) in C:\src\HockeySDK-Windows\HockeySDK_Portable\Model\CrashData.cs:Zeile 197.
   bei HockeyApp.HockeyClient.Deserialize(Stream inputStream) in C:\src\HockeySDK-Windows\HockeySDK_Portable\HockeyClient.cs:Zeile 468.
   bei HockeyApp.HockeyClient.<SendCrashesAndDeleteAfterwardsAsync>d__96.MoveNext() in C:\src\HockeySDK-Windows\HockeySDK_Portable\HockeyClient.cs:Zeile 584.
```

This would make sense as the write throws an unexcpected exception.

When configuring the Client with 
```
HockeyApp.Current.Configure("myappid", true);
```

Exceptions will be caught and swallowed and written correctly to disk. `SendCrashesAsync()` is sending those correctly afterwards.

It seems that Async file operations in the unhandled exception handler of the AppDomain in a Windows Forms app causing a Problem.

**Comment by antwilliams** [comment]
The issue seems to be related to a FileNotFound exception being thrown in the WriteStreamToFileAsync function of [HockeyPlatformHelperWinForms.cs](https://github.com/bitstadium/HockeySDK-Windows/blob/develop/HockeySDK_WinForms45/HockeyPlatformHelperWinForms.cs#L72-L82)

The FileNotFound exception is coming from the isoStore.OpenFile call. I have created a modified version of the WinForms SDK that uses a synchronous handler and the exception is still thrown, however the write function then succeeds and everything works correctly.

So there are two questions here really:
* Why does the UnhandledException handler not like async calls 
* Why is FileNotFound thrown by the isolated storage (but then work anyway)

I'm going to try and dig in to this a bit further, there are a few SO [questions](http://stackoverflow.com/questions/72626/could-not-find-file-when-using-isolated-storage) that are similar to this but don't quite fit the use case here.

**Comment by bvanderw** [comment]
Is there a particular reason why IsolatedStorage is used to store crashes for Windows Forms?

**Comment by mihailsm** [comment]
Windows Forms SDK is not yet published and is not supported, you can contribute to it it, we welcome pull requests as always.
