### ISSUE TITLE
Can't match HockeySDK.UWP nuget package version with GitHub source code version

### ISSUE THREAD

**Issue by jaccus** [bitstadium/HockeySDK-Windows#40]
Recent [HockeySDK.UWP nuget](https://www.nuget.org/packages/HockeySDK.UWP/) package versions are in the version range of `3.1.0`, `3.1.1` and `3.2.1`.

`HockeySDK-Windows` repository has outdated releases/tags with latest version at `2.2.2`. Also recent commits version bumps are in the range of `2.x`.

Considering that HockeySDK.UWP nuget packages point their Project URL to this Git repo, an explaination on how you guys version things would be nice.

**Comment by lumaxis** [comment]
Hey @jaccus, thanks for bringing this up!

We haven't pushed tags for these versions yet but will probably do that very soon. We probably won't do proper releases on Github since these prerelease SDKs only work for users enrolled in [Preseason](http://hockeyapp.net/preseason/) and having them very visible on Github might confuse people unnecessarily. 

The code itself is already public btw: https://github.com/bitstadium/HockeySDK-Windows/tree/preseason

**Comment by jaccus** [comment]
Missed the preseason branch when sniffing around, thanks!
