### ISSUE TITLE
HockeySDK.WinRT 4.1.3 removes stack trace and message

### ISSUE THREAD

**Issue by negue** [bitstadium/HockeySDK-Windows#65]
Nearly every crash I get on my app doesn't have a stacktrace or message.

I don't know if its just on WinRT but if you access the Property of an exception once it's "gone" on the 2nd access.

Back then, I had to use `ExceptionDispatchinfo` while sending the crashes to BugSense, then it worked, so maybe it could fix it in Hockey too?

**Comment by izikl** [comment]
@negue what exactly do you mean by "removes stack trace"? Is it not showing in the HockeyApp UI?

**Comment by IanSavchenko** [comment]
I was having the same problem in my WP8.1 app. Originally I had my own logging of crashes to local log with either `TaskScheduler.UnobservedTaskException += OnTaskSchedulerUnobservedTaskException;` 
or by attaching to event `Windows.UI.Xaml.Application.UnhandledException`. I added HockeyApp to the project but stack traces in crashes were reported empty on the portal ("Stacktrace cannot be displayed").

One day I decided to figure out what is going on, otherwise HockeyApp was not much of use for me. It seems that StackTrace property of unhandled exception returns a value only when accessed the first time. So I had to make sure that HockeyApp gets access first by adding my local logging handlers with `RegisterCustomUnhandledExceptionLogic` and `RegisterCustomUnobserveredTaskExceptionLogic`. Of course, I had to sacrifice local logging a bit, but crash analytics is more important to me in this situation.

It doesn't seem to be a bug of HockeyApp, but a really nasty behavior of WinRT. I think it should be clarified somewhere.

**Comment by deanihansen** [comment]
I can confirm what's mentioned above. The easiest repro is to create exceptions and throw a dialog based on the exception message. If you access the exception in your code, you won't see the StackTrace in the  HockeyApp dashboard.
```
 private async void OnUnhandledException(object sender, UnhandledExceptionEventArgs e)
 {
     await new MessageDialog(e.Exception.Message).ShowAsync();
     HockeyClient.Current.TrackException(e.Exception);
     Debug.WriteLine(e.Exception);
 }

 private async void OnUnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs e)
 {
     await new MessageDialog(e.Exception.Message).ShowAsync();
     HockeyClient.Current.TrackException(e.Exception);
     Debug.WriteLine(e.Exception);
 }
```

**Comment by elamalani** [comment]
Closing this issue as it is unrelated to HockeyApp Windows SDK.
